### ISSUE TITLE
Player Color?

### ISSUE THREAD

**Issue by Frouk3** [Cazka/diepAPI#35]
It seems that there's no Player team color, i wanted to make aimbot but i think that's impossible to do

**Comment by Cazka** [comment]
Hey and thanks for trying out diepAPI.

What you are trying to do is not impossible.
You can find the color of a player in the `extras` property.
For example this will show you your own team color:

diepAPI v2.1.1
```js
window.diepAPI.entityManager.getPlayer().extras.color
```

You can find all team colors here https://github.com/Cazka/diepAPI/blob/bc4a4aed6d8dae237cdea1892773394589429546/src/entity.ts#L17
