### ISSUE TITLE
question ) Is there a way to check player's health value?

### ISSUE THREAD

**Issue by gurumnyang** [Cazka/diepAPI#38]
I need to check my raw health value in diep.
I know how to enable raw_health_value. But I don't know how to use that values in a script.
Is there a way to check player's health value?
![image](https://user-images.githubusercontent.com/62387796/166288592-ee1f620f-6156-493e-8a54-5aa968b95ba0.png)

& it's not working
```
CanvasKit.hook('fillRect', (target, thisArg, args) => {
console.log(thisArg.fillStyle);
})
```

**Comment by Cazka** [comment]
no, currently it's not possible to retrieve the health values.
