### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by tariteur** [Cazka/diepAPI#56]
hello,
I was unable to display the extensions
"diepAPI.extensions.entityManager.load()"
but nothing

**Comment by Cazka** [comment]
After `diepAPI.extensions.entityManager.load()`, you can access the entities at `diepAPI.extensions.entityManager.entities`

to visualize the entities use the debugTool

```js
diepAPI.extensions.debugTool.load();
diepAPI.extensions.debugTool.drawAll(true);
```

**Comment by tariteur** [comment]
so fast ty
